### ISSUE TITLE
How into Add AntD plugin to this project setup

### ISSUE THREAD

**Issue by HarishKalepu** [reactGo/reactGo#929] opened 2017-10-26 14:51 UTC
Note: **How into Add AntD plugin to reactGo project**

### Description
- Type:  Question
- Related Issue: AntD Plugin

---------------------------------------------------------------
## Bug
**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce**

----------------------------------------------------------------
## Enhancement

**Reason to enhance/problem with existing solution**

**Suggested enhancement**

**Pros**

**Cons**

-----------------------------------------------------------------

## Question

**How to?**

**Comment by RcKeller** [comment] 2017-10-26 15:06
You can see an example implementation of [babel-plugin-import](https://github.com/RcKeller/STF-Refresh/blob/master/webpack/rules/javascript.js) and [less-loader](https://github.com/RcKeller/STF-Refresh/blob/master/webpack/rules/less.js) in my fork of reactGo. This is not a problem.

**Comment by HarishKalepu** [comment] 2017-10-26 20:12
It help lot and one more you in this STF Refresh project use config packge by this your getting config.get('db') etc where is that config file please help on this please

**Comment by RcKeller** [comment] 2017-10-26 20:32
It's an alternative to drawing from environment variables for config info like ports, secrets etc. [Docs](https://www.npmjs.com/package/config)

There's info on the repo's wiki, and you can review the package docs. Generally speaking, though, you should just reference the repo for the antd/less implementation and then work off reactGo as your boilerplate.

**Comment by slavab89** [comment] 2017-11-05 09:03
I'm closing since its not a issue with this project. We can still continue speaking about it even if the issue is closed.
Moreover, in case you have a specific issue with adding `AntD` plugin, please ask a more specific question so that we'll be able to better understand what you're struggling with.

**Closed by slavab89** 2017-11-05 09:03 UTC
Labels: question

**Comment by Shelyo** [comment] 2018-06-14 10:22
@RcKeller 
Even when using exactly your webpack configuration, the style is not applied. I saw that you manually imported all the style, but not even that works for us.
babel-loader works partially, since in the browser are only the components loaded that we use. However, only the html is inserted, the style is missing.

Does someone have an idea why the style is not shown?
We tried with less, without less, with 'style: true' in the babel-loader, different include/exclude settings, with no style setting (in the babel-loader, to not make it modularily) at all, with webpack 4, but the CSS of external libraries simply does not get loaded in ReactGo. 
Same issue with material UI.
