### ISSUE TITLE
Bug | Heroku: Build failed

### ISSUE THREAD

**Issue by kamish24six** [reactGo/reactGo#910] opened 2017-07-27 18:24 UTC

**Comment by ZeroCho** [comment] 2017-07-31 17:50
Provide description please, or I have to close this issue

**Comment by trda** [comment] 2017-08-03 12:56
- git push heroku master
Counting objects: 21235, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (20202/20202), done.
Writing objects: 100% (21235/21235), 21.85 MiB | 215.00 KiB/s, done.
Total 21235 (delta 5284), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Node.js app detected
remote: 
remote: -----> Build failed
remote:  !     Two different lockfiles found: package-lock.json and yarn.lock
remote: 
remote:        Both npm and yarn have created lockfiles for this application,
remote:        but only one can be used to install dependencies. Installing
remote:        dependencies using the wrong package manager can result in missing
remote:        packages or subtle bugs in production.
remote: 
remote:        - To use npm to install your application's dependencies please delete
remote:          the yarn.lock file.
remote: 
remote:          $ git rm yarn.lock
remote: 
remote:        - To use yarn to install your application's dependences please delete
remote:          the package-lock.json file.
remote: 
remote:          $ git rm package-lock.json
remote:     
remote:        https://kb.heroku.com/why-is-my-node-js-build-failing-because-of-conflicting-lock-files
remote: 
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to pilaty.
remote: 



As far as I understand, there are two lock file. The problem is related with them.

**Comment by ZeroCho** [comment] 2017-08-03 13:09
Yes. Please remove one of them. Heroku cannot build if you have two files at the same time. We are gonna remove one file, but we are now choosing which one to delete.

**Comment by trda** [comment] 2017-08-03 13:34
Yes you are right. I deleted yard.lock file and then it worked.

**Closed** 2017-10-20 09:21 UTC
